---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  CI_DEBUG_TRACE: "true"
  COMPOSE_PROJECT_NAME: homeautomation-plc-build-$CI_JOB_ID

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    paths:
      - build.tgz
  script:
    - ./docker/ci_logic.sh run-build
test:
  stage: test
  artifacts:
    paths:
      - coverage
  dependencies:
    - build
  script:
    - ./docker/ci_logic.sh run-test
