---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  CI_DEBUG_TRACE: "true"
  COMPOSE_PROJECT_NAME: homeautomation-plc-build-$CI_JOB_ID

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    paths:
      - build.tgz
  before_script:
    - cd docker
    - docker compose build
    - docker compose up -d --force-recreate build-env
  script:
    # native platform
    - docker compose exec -w / build-env make -f /source/Makefile native conandir=/prepare/build.venv sourcedir=/source
    - docker compose cp build-env:/build .
    - tar czpf ../build.tgz build
    # Raspberry Pi 3 platform
    - docker compose exec -w / build-env make -f /source/Makefile rpi3 conandir=/prepare/build.venv sourcedir=/source
  after_script:
    - cd docker
    - docker compose rm -sf build-env
    - docker rm $(docker ps -a -f status=exited -q)
test:
  stage: test
  dependencies:
    - build
  before_script:
    - cd docker
    - docker compose build
    - docker compose up -d --force-recreate
    - tar xzf ../build.tgz
    - docker compose cp build build-env:/
  script:
    - docker compose exec -w /source build-env make -f /source/Makefile test-nomemcheck testdir=/build
  after_script:
    - cd docker
    - docker compose rm -sf
    - docker rm $(docker ps -a -f status=exited -q)
