---
tasks:
  - name: main
    interval: 25000  # us
    programs:
      - name: RoofLogic
        type: C++
    mqtt: primary
    io:
      - type: mqtt
        client: primary
        inputs:
          /homeautomation/ground_office_light: ground_office_light
        outputs: {}
      - type: i2c
        bus: /dev/i2c-1
        components:
          3b:  # i2c address
            type: pcf8574
            direction: input
            inputs:
              0: sr_raff_up
              1: sr_raff_down
              2: kizi_2_raff_up
              3: kizi_2_raff_down
          20:  # i2c address
            type: max7311
            direction: output
            outputs:
              0: sr_raff_down
              1: sr_raff_up
              2: kizi_2_raff_down
              3: kizi_2_raff_up
              4: ground_office_light
mqtt:
  primary:
    username: "{{ mqtt_username }}"
    password: "{{ mqtt_password }}"
    address: "{{ mqtt_url }}"
    client_id: roof
