---
tasks:
  - name: main
    interval: 25000  # us
    programs:
      - name: GroundLogic
        type: C++
    io:
      - type: mqtt
        client:
          username: "{{ mqtt_username }}"
          password: "{{ mqtt_password }}"
          address: "{{ mqtt_url }}"
          client_id: ground::main
        inputs: {}
        outputs:
          /homeautomation/ground_office_light: ground_office_light
      - type: i2c
        bus: /dev/i2c-1
        components:
          38:  # i2c address
            type: pcf8574
            direction: input
            inputs:
              1: stairs_light
              2: kitchen_light
              3: charger
              4: deck_light
              5: ground_office_light
              6: u_light
          20:  # i2c address
            type: pcf8574
            direction: output
            outputs:
              0: charger
              1: stairs_light
              2: stairs_light
              3: kitchen_light
              4: deck_light
              5: u_light
