[package]
name = "homeautomation-plc"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-or-later"
publish = false

[[bin]]
name = "homeautomation-plc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
toml = "0.9"
